### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by evg26** [Zud71/elehant_meter#10]
Не работает TEST
![err](https://github.com/user-attachments/assets/05dc52a3-390d-4f4d-bbdd-92067623b10a)

**Comment by Zud71** [comment]
У меня все отлично работает. Вы уверены, что это ошибка от моей интеграции? Вы точно скопировали все файлы и перегрузили НА? Приложите лог.

**Comment by evg26** [comment]
Регистратор: homeassistant.setup
Источник: setup.py:334
Первое сообщение: 14:02:22 (1 сообщений)
Последнее сообщение: 14:02:22

Setup failed for custom integration 'elehant_meter': Unable to import component: cannot import name 'log' from 'custom_components.elehant_meter.const' (/config/custom_components/elehant_meter/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/elehant_meter/__init__.py", line 17, in <module>
    from .const import log
ImportError: cannot import name 'log' from 'custom_components.elehant_meter.const' (/config/custom_components/elehant_meter/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/elehant_meter/__init__.py", line 17, in <module>
    from .const import log
ImportError: cannot import name 'log' from 'custom_components.elehant_meter.const' (/config/custom_components/elehant_meter/const.py)

**Comment by evg26** [comment]
Из зм моей автоматизации может ошибка

Регистратор: homeassistant.components.template.template_entity
Источник: components/template/template_entity.py:199
интеграция: Template ([документация](https://www.home-assistant.io/integrations/template), [проблемы](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+template%22))
Первое сообщение: 14:02:45 (2 сообщений)
Последнее сообщение: 14:02:45

TemplateError('ValueError: Template error: int got invalid input 'unavailable' when rendering template '{{ states('sensor.b0_01_02_01_8b_7f_pokazaniia') | int }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.b0_01_02_01_8b_7f_pokazaniia') | int }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.your_sensor_cold'
TemplateError('ValueError: Template error: int got invalid input 'unavailable' when rendering template '{{ states('sensor.b0_01_02_01_8b_8b_pokazaniia') | int }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.b0_01_02_01_8b_8b_pokazaniia') | int }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.your_sensor_hot'

**Comment by Zud71** [comment]
Обновите init.py. Забыл убрать ненужный импорт...

**Comment by evg26** [comment]
Чудо. Все работает
